package com.ical.calculator.calculatorface;

public class CalCulatorKey {
    public static final String COS = "cos";
    public static final String COSH = "cosh";
    public static final String COS_EPONTITAL_ONE_NEGAVITY = "cos_expontital_one_negavity";
    public static final String CUBE_ROOT = "cube_root";
    public static final String DIGIT = "digit";
    public static final String DIVIDE = "divide";
    public static final String EPONENTITAL_TOW = "eponenttital_tow";
    public static final String EQUALS = "equals";
    public static final String EULER = "euler";
    public static final String EULER_N = "euler_n";
    public static final String EXPONENTIAL_2 = "exponential";
    public static final String EXPONENTIAL_3 = "exponential_three";
    public static final String EXPONENTIAL_N = "exponential_n";
    public static final String EXPONENTIAL_TEN = "exponential_ten";
    public static final String GIAITHUA = "giaithua";
    public static final String LOGA_EULER = "loga_euler";
    public static final String LOGA_TEN = "loga_ten";
    public static final String MINUS = "minus";
    public static final String MODULO = "modulo";
    public static final String MULTIPLY = "multiply";
    public static final String NEGAVITY_FALSE = "negavity_false";
    public static final String NEGAVITY_TRUE = "negavity_true";
    public static final String N_ROOT = "n_toot";
    public static final String ONE_EXPONENTIAL_NEGAVITY = "one_exponential_negavity";
    public static final String PERCENT = "percent";
    public static final String PI = "pi";
    public static final String PLUS = "plus";
    public static final String POWER = "power";
    public static final String RAND = "rand";
    public static final String ROOT = "root";
    public static final String SIN = "sin";
    public static final String SINH = "sinh";
    public static final String SIN_EPONTITAL_ONE_NEGAVITY = "sin_expontital_one_negavity";
    public static final String SQUARE_ROOT = "square_root";
    public static final String TAN = "tan";
    public static final String TANH = "tanh";
    public static final String TAN_EPONTITAL_ONE_NEGAVITY = "tan_expontital_one_negavity";
}
